// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RathalOS.Data.Context;

#nullable disable

namespace RathalOS.Migrations
{
    [DbContext(typeof(Wiki_DbContext))]
    [Migration("20251208173647_EnvironmentVariables")]
    partial class EnvironmentVariables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RathalOS.Data.Models.AssignedTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignedTasks");
                });

            modelBuilder.Entity("RathalOS.Data.Models.MHHCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Decoration")
                        .HasColumnType("int");

                    b.Property<string>("HunterArmor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HunterWeapon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int?>("WikiUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WikiUserId");

                    b.ToTable("MHHCards");
                });

            modelBuilder.Entity("RathalOS.Data.Models.MHHEnvironmentVariables", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentSpecialEdition")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastHolo")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastRare")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSpecial")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalPulls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MHHEnvironmentVariables");
                });

            modelBuilder.Entity("RathalOS.Data.Models.ReleaseDates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasNotified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReleaseDates");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<decimal>("ChannelID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnHold")
                        .HasColumnType("bit");

                    b.Property<string>("TagsCSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("WikiTasks");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiTaskUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Update")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("TaskId");

                    b.ToTable("WikiTaskUpdates");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("UserID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WikiUsers");
                });

            modelBuilder.Entity("RathalOS.Data.Models.AssignedTask", b =>
                {
                    b.HasOne("RathalOS.Data.Models.WikiUser", "Assignee")
                        .WithMany("UserAssignments")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("RathalOS.Data.Models.WikiTask", "Assignment")
                        .WithMany("Assigned")
                        .HasForeignKey("AssignmentId");

                    b.Navigation("Assignee");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("RathalOS.Data.Models.MHHCard", b =>
                {
                    b.HasOne("RathalOS.Data.Models.WikiUser", null)
                        .WithMany("Cards")
                        .HasForeignKey("WikiUserId");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiTask", b =>
                {
                    b.HasOne("RathalOS.Data.Models.WikiUser", "Creator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiTaskUpdate", b =>
                {
                    b.HasOne("RathalOS.Data.Models.WikiUser", "Creator")
                        .WithMany("Updates")
                        .HasForeignKey("CreatorId");

                    b.HasOne("RathalOS.Data.Models.WikiTask", "Task")
                        .WithMany("Updates")
                        .HasForeignKey("TaskId");

                    b.Navigation("Creator");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiTask", b =>
                {
                    b.Navigation("Assigned");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("RathalOS.Data.Models.WikiUser", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("CreatedTasks");

                    b.Navigation("Updates");

                    b.Navigation("UserAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
