// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RathalOS.Data.Context;

#nullable disable

namespace RathalOS.Migrations
{
    [DbContext(typeof(Wiki_DbContext))]
    [Migration("20251110192954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RathalOS.Data.AssignedTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignedTasks");
                });

            modelBuilder.Entity("RathalOS.Data.WikiTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnHold")
                        .HasColumnType("bit");

                    b.Property<string>("TagsCSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("WikiTasks");
                });

            modelBuilder.Entity("RathalOS.Data.WikiTaskUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Update")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("TaskId");

                    b.ToTable("WikiTaskUpdates");
                });

            modelBuilder.Entity("RathalOS.Data.WikiUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("UserID")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WikiUsers");
                });

            modelBuilder.Entity("RathalOS.Data.AssignedTask", b =>
                {
                    b.HasOne("RathalOS.Data.WikiUser", "Assignee")
                        .WithMany("UserAssignments")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("RathalOS.Data.WikiTask", "Assignment")
                        .WithMany("Assigned")
                        .HasForeignKey("AssignmentId");

                    b.Navigation("Assignee");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("RathalOS.Data.WikiTask", b =>
                {
                    b.HasOne("RathalOS.Data.WikiUser", "Creator")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("RathalOS.Data.WikiTaskUpdate", b =>
                {
                    b.HasOne("RathalOS.Data.WikiUser", "Creator")
                        .WithMany("Updates")
                        .HasForeignKey("CreatorId");

                    b.HasOne("RathalOS.Data.WikiTask", "Task")
                        .WithMany("Updates")
                        .HasForeignKey("TaskId");

                    b.Navigation("Creator");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("RathalOS.Data.WikiTask", b =>
                {
                    b.Navigation("Assigned");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("RathalOS.Data.WikiUser", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("Updates");

                    b.Navigation("UserAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
